name: Reusable API Test Workflow

on:
  workflow_call:  # Enables reuse

jobs:
  api-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Sanity API Tests
        run: mvn test -PSanity
